config/routes.rb
Rails.application.routes.draw do

  post '/rate' => 'rater#create', :as => 'rate'
  get 'backoffice', to: 'backoffice/dashboard#index'
  
  namespace :backoffice do
    resources :send_mail, only: [:edit, :create]
    resources :categories, except: [:show, :destroy]
    resources :admins, except: [:show]
    resources :diagrams, only: [:index]
    get 'dashboard', to: 'dashboard#index' 
    
  end
  
  namespace :site do
    get 'home', to: 'home#index'
    get 'search', to: 'search#ads'
    resources :ad_details, only: [:show]
    resources :categories, only: [:show]
    resources :comments, only: [:create]
    
    namespace :profile do
      resources :dashboard, only: [:index]
      resources :ads, except: [:destroy]
      resources :my_data, only: [:edit, :update]
    end
  end
  
  devise_for :admins, :skip => [:registration]
  devise_for :members, controllers: { sessions: 'members/sessions', registrations: 'members/registrations' }
  root 'site/home#index'
  

end

app/controllers/backoffice/admins_controller.rb
class Backoffice::AdminsController < BackofficeController
  before_action :set_admin, only: [:edit, :update, :destroy]
  # after_action :verify_authorized, only: [:new, :destroy]
  # after_action :verify_policy_scoped, only: :index
  
  def index
      @admins = policy_scope(Admin)
  end
  
  
  def new
    @admin = Admin.new
    authorize @admin
  end
  
  def create
    @admin = Admin.create(params_admin)
    if @admin.save
        redirect_to backoffice_admins_path, notice: "Admin (#{@admin.email}) save successful"
    else
       render :new
     end
  end
  
  def update
    
    if @admin.update(params_admin)
      AdminMailer.update_email(current_admin, @admin).deliver_now
      redirect_to backoffice_admins_path, notice: "Admin (#{@admin.email}) update successful"
    else
      render :edit
    end
  end
  
  def edit
  end
  
  def destroy
    authorize @admin
    admin_email = @admin.email
    
    if @admin.destroy
      redirect_to backoffice_admins_path, notice: "Admin (#{admin_email}) destroyed successful"
    else
      render :index
    end

  end
  
  private
    def set_admin
      @admin = Admin.find(params[:id])
    end
  
    def params_admin

      pass = params[:admin][:password]
      pass_conf = params[:admin][:password_confirmation] 
    
      if pass.blank? && pass_conf.blank?
        params[:admin].except!(:password, :password_confirmation)
      end
      unless @admin.blank?
        params.require(:admin).permit(policy(@admin).permitted_attributes)
      else
        params.require(:admin).permit(:name, :email, :role, :password, :password_confirmation)
      end
    end
end

app/controllers/backoffice/categories_controller.rb
class Backoffice::CategoriesController < BackofficeController
  before_action :set_category, only: [:edit, :update]
  def index
    @categories = Category.all
  end
  
  
  def new
    @category = Category.new
  end
  
  def create
    @category = Category.create(params_category)
    if @category.save
        redirect_to backoffice_categories_path, notice: "Category (#{@category.description}) save successful"
    else
       render :new
     end
  end
  
  def update
    if @category.update(params_category)
      redirect_to backoffice_categories_path, notice: "Category (#{@category.description}) update successful"
    else
      render :edit
    end
  end
  
  def edit
    
  end
  
  private
    def set_category
      @category = Category.find(params[:id])
    end
  
    def params_category
      params.require(:category).permit(:description)
    end
  
end

app/controllers/backoffice/dashboard_controller.rb
class Backoffice::DashboardController < BackofficeController
  def index
  end
end

app/controllers/backoffice/diagrams_controller.rb
class Backoffice::DiagramsController < BackofficeController
    def index
        %x(bundle exec erd --filename='public/diagram')
    end
end

app/controllers/backoffice/send_mail_controller.rb
class Backoffice::SendMailController < ApplicationController
   
    def edit
       @admin = Admin.find(params[:id]) 
    end
    
    def create
    
    begin
    
    AdminMailer.send_email(current_admin, params[:'recipient-text'], params[:'subject-text'], params[:'message-text']).deliver_now
    
    @notify_message = "Email enviado com sucesso"
    @notify_flag = "success"
    rescue
    @notify_message = "Erro ao enviar email, tente novamente."
    @notify_flag = "error"
    end
    # Método padrão de recebimento, mas é bom constar.
    respond_to do |format|
        format.js
    end
    
    end
end

app/controllers/backoffice_controller.rb
class  BackofficeController < ApplicationController
  before_action :authenticate_admin!
  layout "backoffice"
  
  def pundit_user
    current_admin
  end
end

app/helpers/backoffice/admins_helper.rb
module Backoffice::AdminsHelper

  OptionsForRole = Struct.new(:id, :description)

    def options_for_role
      Admin.roles_i18n.map do |key, value|
        OptionsForRole.new(key, value)
    end
  end

end

app/helpers/backoffice/categories_helper.rb
module Backoffice::CategoriesHelper
end

app/helpers/backoffice/dashboard_helper.rb
module Backoffice::DashboardHelper
end

app/helpers/backoffice/diragrams_helper.rb
module Backoffice::DiragramsHelper
end

app/helpers/backoffice/send_mail_helper.rb
module Backoffice::SendMailHelper
end

app/views/backoffice/admins/edit.html.erb
<%= render partial: 'backoffice/admins/shared/form', locals: {action: "Editing Administrator"}%>

app/views/backoffice/admins/index.html.erb
<h1 class="page-header">Admins</h1>
  <!-- /.row -->
<div class="row">
  <div class="col-lg-10">
      <div class="panel panel-default">
          <div class="panel-heading">
              Listing Admins
                <%= link_to new_backoffice_admin_path, 
                  class: "btn btn-success btn-circle pull-right", style: "margin-top: -5px" do%>
                    <i class="fa fa-plus"></i>
                <%end%>
          </div>
          <!-- /.panel-heading -->
          <div class="panel-body">
              <div class="table-responsive">
                  <table class="table table-striped table-bordered table-hover">
                      <thead>
                          <tr>
                              <th>#</th>
                              <th>Name</th>
                              <th>Email</th>
                              <th>Tipo de Acesso</th>
                              <th></th>
                          </tr>
                      </thead>
                      <tbody>
                        <% @admins.each do |admin| %>
                          <tr>
                              <td><%= admin.id %></td>
                              <td><%= admin.name %></td>
                              <td><%= admin.email%></td>
                              <td><%= admin.role_i18n%></td>
                              <td width="120px">
                                  
                                  <%= link_to edit_backoffice_send_mail_path(admin), class: "btn btn-info btn-circle", remote: true do%>
                                    <i class="fa fa-envelope"></i>
                                  <%end%>
                                  
                                  <%= link_to edit_backoffice_admin_path(admin), class: "btn btn-primary btn-circle" do%>
                                    <i class="fa fa-list"></i>
                                  <%end%>
                                  
                                  <% if (current_admin.id == admin.id) || policy(@admins).destroy? %>
                                    <button type="button" class="btn btn-danger btn-circle" disabled="disabled">
                                      <i class="fa fa-times"></i>
                                    </button>
                                  <%else %>
                                    <%= link_to backoffice_admin_path(admin), method: :delete, 
                                      class: "btn btn-danger btn-circle", data: {confirm: "Really destroy (#{admin.email})?"} do %>
                                        <i class="fa fa-times"></i>
                                    <% end %>                                    
                                  <%end%>
                              </td>
                          </tr>
                        <%end%>
                      </tbody>
                  </table>
              </div>
              <!-- /.table-responsive -->
          </div>
        <!-- /.panel-body -->
    </div>
  <!-- /.panel -->
</div>


<%= render partial: "backoffice/admins/shared/send_mail" %>

app/views/backoffice/admins/new.html.erb
<%= render partial: 'backoffice/admins/shared/form', locals: {action: "New Administrator"}%>