config/routes.rb
Rails.application.routes.draw do

  post '/rate' => 'rater#create', :as => 'rate'
  get 'backoffice', to: 'backoffice/dashboard#index'
  
  namespace :backoffice do
    resources :send_mail, only: [:edit, :create]
    resources :categories, except: [:show, :destroy]
    resources :admins, except: [:show]
    resources :diagrams, only: [:index]
    get 'dashboard', to: 'dashboard#index' 
    
  end
  
  namespace :site do
    get 'home', to: 'home#index'
    get 'search', to: 'search#ads'
    resources :ad_details, only: [:show]
    resources :categories, only: [:show]
    resources :comments, only: [:create]
    
    namespace :profile do
      resources :dashboard, only: [:index]
      resources :ads, except: [:destroy]
      resources :my_data, only: [:edit, :update]
    end
  end
  
  devise_for :admins, :skip => [:registration]
  devise_for :members, controllers: { sessions: 'members/sessions', registrations: 'members/registrations' }
  root 'site/home#index'
  

end

app/models/ad.rb
class Ad < ActiveRecord::Base
  
  ratyrate_rateable 'quality'
  
  before_save :md_to_html
  
  belongs_to :member
  belongs_to :category, counter_cache: true
  has_many :comments
  
  #Validates
  validates :title, :description_md, :description_short, :price, :category, :finish_date, presence: true
  
  scope :descending_order, -> () {order(created_at: :desc)}
  scope :search, -> (q, page) { where("title LIKE ?", "%#{q}%").page(page).per(6) }
  
  scope :random, ->(quantity) {
    if Rails.env.production?
      limit(quantity).order("RAND()") # MySQL
    else
      limit(quantity).order("RANDOM()") # SQLite
    end
  }  
  
  has_attached_file :picture, styles: { large: "800x300#", medium: "320x150#", thumb: "100x100>" }, 
                                      default_url: "/images/:style/missing.png"
  validates_attachment_content_type :picture, content_type: /\Aimage\/.*\z/
  
  # gem Money_rails
  monetize :price_cents
  
  private
  
  def md_to_html
  
    options = {
      filter_html: true,
      link_attributes: {
        rel: "nofollow",
        target: "_blank"
      }
    }

    extensions = {
      space_after_headers: true,
      autolink: true
    }

  renderer = Redcarpet::Render::HTML.new(options)
  markdown = Redcarpet::Markdown.new(renderer, extensions)

  self.description = markdown.render(self.description_md)
  end
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  
  enum role: [:full_access, :restricted_access]
  
  scope :with_full_access, -> { where(role: 0) }
  scope :with_restricted_access, -> { where(role: 1) }
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

end

app/models/average_cache.rb
class AverageCache < ActiveRecord::Base
  belongs_to :rater, :class_name => "Member"
  belongs_to :rateable, :polymorphic => true
end

app/models/category.rb
class Category < ActiveRecord::Base
  
  has_many :ads
  
  validates :description, presence: true
  
  include FriendlyId
  friendly_id :description, use: :slugged

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :member
  belongs_to :ad
end

app/models/member.rb
class Member < ActiveRecord::Base
  
  ratyrate_rater
  
  has_one :profile_member
  
  accepts_nested_attributes_for :profile_member
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/overall_average.rb
class OverallAverage < ActiveRecord::Base
  belongs_to :rateable, :polymorphic => true
end

app/models/profile_member.rb
class ProfileMember < ActiveRecord::Base
    
    belongs_to :member
    
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, :class_name => "Member"
  belongs_to :rateable, :polymorphic => true

  #attr_accessible :rate, :dimension

end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  before_filter :store_current_location, :unless => :devise_controller? 
  
  include Pundit
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  layout :layout_by_resource
  
  
  protected
  
  def layout_by_resource
    if devise_controller? && resource_name == :admin
      "backoffice_devise"
    elsif devise_controller? && resource_name == :member
      "member_devise"
    else
      "application"
    end
  end
  
  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(request.referrer || root_path)
  end

  private
  def store_current_location
    store_location_for(:member, request.url)
  end
end

app/controllers/backoffice_controller.rb
class  BackofficeController < ApplicationController
  before_action :authenticate_admin!
  layout "backoffice"
  
  def pundit_user
    current_admin
  end
end

app/controllers/rater_controller.rb
class RaterController < ApplicationController

  def create
    if member_signed_in?
      obj = params[:klass].classify.constantize.find(params[:id])
      obj.rate params[:score].to_f, current_member, params[:dimension]

      render :json => true
    else
      render :json => false
    end
  end
end

app/controllers/site_controller.rb
class  SiteController < ApplicationController
  layout "site"
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user
    current_member
  end
end

app/helpers/member_helper.rb
module MemberHelper
end

app/helpers/site/ad_details_helper.rb
module Site::AdDetailsHelper
end

app/helpers/site/comments_helper.rb
module Site::CommentsHelper
end

app/helpers/site/home_helper.rb
module Site::HomeHelper
end

app/helpers/site/search_helper.rb
module Site::SearchHelper
end

app/views/backoffice/admins/shared/_form.html.erb
<h1 class="page-header">Admin</h1>
<%= render partial: "shared/errors", locals: { obj: @admin} %>
 <!-- /.row -->
<div class="row">
  <div class="col-lg-10">
  <div class="panel panel-default">
      <div class="panel-heading">
          <%= action %>
      </div>
      <!-- /.panel-heading -->
      <div class="panel-body">
          <%= form_for([:backoffice, @admin]) do |f| %>
          <div class="form-group">
              <div class="form-group">  
                <label>Name</label>
                <%= f.text_field :name, class: "form-control", placeholder: "Name", autofocus: true%>
              </div>
              <div class="form-group">
                <%= f.label 'Email' %>
                <%= f.text_field :email, class: "form-control", placeholder: "Email"%>
              </div>
              <% if policy(@admin).edit? %>
                <div class="form-group">
                  <%= f.label 'Tipo de acesso' %>
                  <%= f.collection_radio_buttons(:role, options_for_role, :id, :description) do |b| %>
                    <div class="form-group">
                     <%= b.label {b.radio_button + b.text} %>
                    </div>
                  <%end%>
                </div>
              <%end%>
              <label>Password</label>
              <%= f.password_field :password, class: "form-control", placeholder: "Password"%>
              <label>Password Confirmation</label>
              <%= f.password_field :password_confirmation, class: "form-control", placeholder: "Password Confirmation"%>
          </div>
              <button type="submit" class="btn btn-default">Submit</button>
        <%end%>
      </div>
      <!-- /.panel-body -->
  </div>
    <!-- /.panel -->
</div>

app/views/backoffice/admins/shared/_send_mail.html.erb
<div class="modal fade" id="sendMailModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title" id="exampleModalLabel">New message</h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= form_tag(backoffice_send_mail_index_path, remote: true) do %>
          <div class="form-group">
            <label for="recipient-name" class="col-form-label">Recipient:</label>
            <input type="text" class="form-control" id="recipient-name" readonly="readonly">
          </div>
          <div class="form-group">
            <label for="subject-text" class="col-form-label">Subject:</label>
            <%= text_field_tag(:"subject-text", nil, class: "form-control", required: "required") %>
          </div>
          <div class="form-group">
            <label for="message-text" class="col-form-label">Message:</label>
            <%= text_area_tag(:"message-text", nil, class: "form-control", required: "required") %>
          </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <%= submit_tag 'Send Message', class: "btn btn-primary" %>
      </div>
      <%end%>
    </div>
  </div>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="alert alert-danger alert-dismissable">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">x</button>
   <ul>
      <% obj.errors.full_messages.each do |message| %>
        <li><%= message%></li>
      <%end%>
    </ul>
  </div>
<%end%>

app/views/shared/_notifications.html.erb
<% if notice %>
      <script>
        $.notify("<%= notice%>", { className: 'success', globalPosition: 'top-center' });
      </script>
<%end%>
<% if alert %>
      <script>
        $.notify("<%= alert%>", "error");
      </script>
<%end%>
    