config/routes.rb
Rails.application.routes.draw do

  post '/rate' => 'rater#create', :as => 'rate'
  get 'backoffice', to: 'backoffice/dashboard#index'
  
  namespace :backoffice do
    resources :send_mail, only: [:edit, :create]
    resources :categories, except: [:show, :destroy]
    resources :admins, except: [:show]
    resources :diagrams, only: [:index]
    get 'dashboard', to: 'dashboard#index' 
    
  end
  
  namespace :site do
    get 'home', to: 'home#index'
    get 'search', to: 'search#ads'
    resources :ad_details, only: [:show]
    resources :categories, only: [:show]
    resources :comments, only: [:create]
    
    namespace :profile do
      resources :dashboard, only: [:index]
      resources :ads, except: [:destroy]
      resources :my_data, only: [:edit, :update]
    end
  end
  
  devise_for :admins, :skip => [:registration]
  devise_for :members, controllers: { sessions: 'members/sessions', registrations: 'members/registrations' }
  root 'site/home#index'
  

end

app/models/ad.rb
class Ad < ActiveRecord::Base
  
  ratyrate_rateable 'quality'
  
  before_save :md_to_html
  
  belongs_to :member
  belongs_to :category, counter_cache: true
  has_many :comments
  
  #Validates
  validates :title, :description_md, :description_short, :price, :category, :finish_date, presence: true
  
  scope :descending_order, -> () {order(created_at: :desc)}
  scope :search, -> (q, page) { where("title LIKE ?", "%#{q}%").page(page).per(6) }
  
  scope :random, ->(quantity) {
    if Rails.env.production?
      limit(quantity).order("RAND()") # MySQL
    else
      limit(quantity).order("RANDOM()") # SQLite
    end
  }  
  
  has_attached_file :picture, styles: { large: "800x300#", medium: "320x150#", thumb: "100x100>" }, 
                                      default_url: "/images/:style/missing.png"
  validates_attachment_content_type :picture, content_type: /\Aimage\/.*\z/
  
  # gem Money_rails
  monetize :price_cents
  
  private
  
  def md_to_html
  
    options = {
      filter_html: true,
      link_attributes: {
        rel: "nofollow",
        target: "_blank"
      }
    }

    extensions = {
      space_after_headers: true,
      autolink: true
    }

  renderer = Redcarpet::Render::HTML.new(options)
  markdown = Redcarpet::Markdown.new(renderer, extensions)

  self.description = markdown.render(self.description_md)
  end
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  
  enum role: [:full_access, :restricted_access]
  
  scope :with_full_access, -> { where(role: 0) }
  scope :with_restricted_access, -> { where(role: 1) }
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

end

app/models/average_cache.rb
class AverageCache < ActiveRecord::Base
  belongs_to :rater, :class_name => "Member"
  belongs_to :rateable, :polymorphic => true
end

app/models/category.rb
class Category < ActiveRecord::Base
  
  has_many :ads
  
  validates :description, presence: true
  
  include FriendlyId
  friendly_id :description, use: :slugged

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :member
  belongs_to :ad
end

app/models/member.rb
class Member < ActiveRecord::Base
  
  ratyrate_rater
  
  has_one :profile_member
  
  accepts_nested_attributes_for :profile_member
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/overall_average.rb
class OverallAverage < ActiveRecord::Base
  belongs_to :rateable, :polymorphic => true
end

app/models/profile_member.rb
class ProfileMember < ActiveRecord::Base
    
    belongs_to :member
    
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, :class_name => "Member"
  belongs_to :rateable, :polymorphic => true

  #attr_accessible :rate, :dimension

end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  before_filter :store_current_location, :unless => :devise_controller? 
  
  include Pundit
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  layout :layout_by_resource
  
  
  protected
  
  def layout_by_resource
    if devise_controller? && resource_name == :admin
      "backoffice_devise"
    elsif devise_controller? && resource_name == :member
      "member_devise"
    else
      "application"
    end
  end
  
  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(request.referrer || root_path)
  end

  private
  def store_current_location
    store_location_for(:member, request.url)
  end
end

app/controllers/backoffice_controller.rb
class  BackofficeController < ApplicationController
  before_action :authenticate_admin!
  layout "backoffice"
  
  def pundit_user
    current_admin
  end
end

app/controllers/members/registrations_controller.rb
class Members::RegistrationsController < Devise::RegistrationsController
    
    before_filter :configure_permitted_parameters
    
    def new
        build_resource({})
        resource.build_profile_member
        respond_with self.resource
    end
    
    protected
    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, 
            keys: [
                :member, :password, :password_confirmation, 
                :profile_member_attributes => [:first_name, :second_name]
            ]
        )
    end
end

app/controllers/members/sessions_controller.rb
class Members::SessionsController < Devise::SessionsController
  
  def new
    super do |resource|
      resource.build_profile_member
    end
  end
  
  protected
    def after_sign_in_path_for(resource)
      stored_location = stored_location_for(resource)
      if stored_location.match("site/ad_detail")
        stored_location
      else
        site_profile_dashboard_index_path
      end
    end
end

app/controllers/rater_controller.rb
class RaterController < ApplicationController

  def create
    if member_signed_in?
      obj = params[:klass].classify.constantize.find(params[:id])
      obj.rate params[:score].to_f, current_member, params[:dimension]

      render :json => true
    else
      render :json => false
    end
  end
end

app/controllers/site/home_controller.rb
class Site::HomeController < SiteController
  def index
    @categories = Category.order(:description)
    @ads = Ad.descending_order().page(params[:page]).per(6)
    if Rails.env.production?
      @carousel = Ad.limit(3).order("RAND()")
    else
      @carousel = Ad.limit(3).order("RANDOM()")
    end
  end
end

app/controllers/site_controller.rb
class  SiteController < ApplicationController
  layout "site"
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user
    current_member
  end
end

app/helpers/member_helper.rb
module MemberHelper
end

app/helpers/members/registrations_helper.rb
module Members::RegistrationsHelper
end

app/helpers/site/ad_details_helper.rb
module Site::AdDetailsHelper
end

app/helpers/site/categories_helper.rb
module Site::CategoriesHelper
end

app/helpers/site/comments_helper.rb
module Site::CommentsHelper
end

app/helpers/site/home_helper.rb
module Site::HomeHelper
end

app/helpers/site/search_helper.rb
module Site::SearchHelper
end

app/views/members/shared/_form.html.erb
<div class="container">    
    <div id="loginbox" style=<%= style1 %> class="mainbox col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">                    
        <div class="panel panel-info" >
                <div class="panel-heading">
                    <div class="panel-title">Sign In</div>
                    <div style="float:right; font-size: 80%; position: relative; top:-10px">
                      <%= link_to "Forgot password?", new_member_password_path %>
                      </div>
                </div>     

                <div style="padding-top:30px" class="panel-body" >

                    <div style="display:none" id="login-alert" class="alert alert-danger col-sm-12"></div>
                        
                    <%= form_for(resource, as: resource_name, url: session_path(resource_name),
                                    html: {role: "form", class: "form-horizontal"}) do |f| %>            
                        <div style="margin-bottom: 25px" class="input-group">
                                    <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
                                    <%= f.email_field :email, autofocus: true, 
                                    autocomplete: "email", class: "form-control", 
                                    placeholder: "E-mail", type: "email", autofocus: "autofocus"%>
                                </div>
                            
                        <div style="margin-bottom: 25px" class="input-group">
                                    <span class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></span>
                                    <%= f.password_field :password, 
                                    autocomplete: "current-password", 
                                    class: "form-control", placeholder: "Password", type: "password" %>
                                </div>
                                

                            
                        <div class="input-group">
                                  <div class="checkbox">
                                    <label>
                                        <%= f.check_box :remember_me,  type: "checkbox"%>Remember Me
                                    </label>
                                  </div>
                                </div>


                            <div style="margin-top:10px" class="form-group">
                                <!-- Button -->
                                <div class="col-sm-12 controls">
                                  <%= f.submit "Log in", class: "btn btn-success"%>
                                  <a id="btn-fblogin" href="#" class="btn btn-primary">Login with Facebook</a>
                                </div>
                            </div>


                            <div class="form-group">
                                <div class="col-md-12 control">
                                    <div style="border-top: 1px solid#888; padding-top:15px; font-size:85%" >
                                        Don't have an account! 
                                    <a href="#" onClick="$('#loginbox').hide(); $('#signupbox').show()">
                                        Sign Up Here
                                    </a>
                                    </div>
                                </div>
                            </div>    
                        <%end%>    



                    </div>                     
                </div>  
    </div>
    
    
    
    
<div id="signupbox" style=<%=style2%> class="mainbox col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
  <div class="panel panel-info">
    <div class="panel-heading">
        <div class="panel-title">Sign Up</div>
        <div style="float:right; font-size: 85%; position: relative; top:-10px"><a id="signinlink" href="#" onclick="$('#signupbox').hide(); $('#loginbox').show()">Sign In</a></div>
    </div>  
    <div class="panel-body" >
        <%= form_for(resource, as: resource_name, 
          url: registration_path(resource_name), 
            html: {class:"form-horizontal", role:"form"}) do |f| %>    
            
            <% unless devise_error_messages!.blank? %>
              <div id="signupalert" style="display:none" class="alert alert-danger">
                  <p>Error:</p>
                  <span></span>
              </div>
            <%end%>
            
            <div class="form-group">
                <label for="email" class="col-md-3 control-label">Email</label>
                <div class="col-md-9">
                    <%= f.email_field :email, autofocus: true,
                      autocomplete: "email", placeholder:"E-mail",
                        class: "form-control"%>
                </div>
            </div>
            
            <%= f.fields_for :profile_member do |profile_fields|%>
                <div class="form-group">
                    <label for="firstname" class="col-md-3 control-label">First Name</label>
                    <div class="col-md-9">
                        <%= profile_fields.text_field :first_name, class:"form-control", placeholder: "First Name" %>
                    </div>
                </div>
                <div class="form-group">
                    <label for="firstname" class="col-md-3 control-label">Second Name</label>
                    <div class="col-md-9">
                        <%= profile_fields.text_field :second_name, class:"form-control", placeholder: "Second Name" %>
                    </div>
                </div>
            <%end%>
            
            <div class="form-group">
                <label for="password" class="col-md-3 control-label">Password</label>
                <div class="col-md-9">
                    <%= f.password_field :password, class: "form-control", placeholder:"Password"%>
                </div>
            </div>
            
            <div class="form-group">
                <label for="password_confirmation" class="col-md-3 control-label">Password Confirmation</label>
                <div class="col-md-9">
                    <%= f.password_field :password_confirmation, class: "form-control", placeholder:"Password Confirmation"%>
                </div>
            </div>
                
            <div class="form-group">
                <!-- Button -->                                        
                <div class="col-md-offset-3 col-md-9">
                    <%= submit_tag "Sing up", class: "btn btn-info" do %>
                      <i class="icon-hand-right"></i>
                    <%end%>
                </div>
            </div>
            
        <%end%>
     </div>
  </div>
 </div> 
</div>

<% flash.each do |key, value| %>
    <script>
        $.notify("<%= value %>", "info")
    </script>
<%end%>

app/views/members/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>